version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "id-generator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5bnn713hsegw"
s3_prefix = "id-generator"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

